version: 2
jobs:
  build:
    docker:
      - image: oraclelinux:7.3
    steps:
      - checkout
      - run:
          name: notify to slack
          command: |
            curl -X POST \
            $SLACK_WEBHOOK_URL \
            -H 'content-type: application/json' \
            -d '{
              "text": "Build started!"
            }'

      - run:
          name: Print the Current Time
          command: date

