version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: notify to slack
          command: |
            curl -X POST \
            "https://hooks.slack.com/services/$SLACK_WEBHOOK_URL" \
            -H 'content-type: application/json' \
            -d '{
              "text": "Build started!"
            }'

      - run:
          name: Print the Current Time
          command: date

